### ISSUE TITLE
ShadowView Pimpl

### ISSUE THREAD

**Issue by nick-thompson** [nick-thompson/react-juce#179]
Following #145, I'd like to refactor our ShadowView class in the same way we just did for EcmascriptEngine. In particular, our ShadowView interface should have no mention of Yoga, as Yoga is just an implementation detail. Inside `ShadowView.cpp` we'll include the Yoga headers, do any compiler warnings dance we need there, and satisfy the `ShadowView` interface with a `Pimpl` tailored to Yoga.

For one this is a cleaner design pattern, and two if we ever want to support a layout engine besides Yoga (e.g. one that supports CSS Grid), we'll be able to easily add a second Pimpl and a compiler flag to choose.

**Comment by JoshMarler** [comment]
@nick-thompson , shall we close this for the moment and potentially revisit as part of an "add CSS grid support" or similar?

**Comment by nick-thompson** [comment]
Woo!

Yea, let's close. We'll revisit the idea for another layout engine or grid support when it becomes a hot feature request
