### ISSUE TITLE
How to use Hermes

### ISSUE THREAD

**Issue by gabriel-earle** [nick-thompson/react-juce#314]
Thanks a ton for a wonderful package.  What are the steps I can use to choose Hermes as the JS engine?

Gabe

**Comment by shih1** [comment]
I had to add configs to the `Preprocessor Definitions` and `Header Search Paths` recently to get hermes to work

`Preprocessor` 

```
REACTJUCE_USE_HERMES=1
```

`Headers`

```
**/react-juce/react_juce/hermes/API/
**/react-juce/react_juce/hermes/public/
**/react-juce/react_juce/hermes/API/jsi/
```

Header locations will change depending on system.

**Comment by gabriel-earle** [comment]
Thank you!! I was able to actually figure it out with the help of ChatGPT 4.  It was able to scan this Repo using the browser, use its deep knowledge of C++, a tiny bit of knowledge of Hermes, and everything else to help me get to a solution.  I am also compiling through Projucer so that added a ton of work.  CMake is probably a better choice if using Hermes, but if anyone stumbles upon this who is using Projucer, you'll need to do the following:
- build Hermes manually.  It's not too hard, just compile using the python script in utils/build, and then build by changing directory to the build directory that was created and using ninja.
- In Projucer, in your Exporter settings, add all of these to "external libraries to link".  Each one of these is a part of hermes that corresponds to one lib file (ie hermesSupport corresponds to libhermesSupport.a):
```
hermesapi
hermesSupport
hermesVMRuntime
hermesADT
hermesPlatform
hermesPlatformUnicode
hermesBackend
hermesHBCBackend
hermesFrontend
hermesOptimizer
hermesSourceMap
hermesFrontEndDefs
hermesAST
hermesInst
hermesRegex
hermesParser
LLVHSupport
jsi
dtoa
```
- Then in your target (I've only done debug so far), add all of the "external library search paths".  These are just the directories that directly contain each of the lib files above.  I’ve only tested it as an absolute path.  I'm just gonna cut everything off before the hermes submodule for simplicity.
```
hermes/utils/build/build/API/hermes
hermes/utils/build/build/lib/Support
hermes/utils/build/build/lib/VM
hermes/utils/build/build/lib/ADT
hermes/utils/build/build/lib/Platform
hermes/utils/build/build/lib/Platform/Unicode
hermes/utils/build/build/lib/BCGen
hermes/utils/build/build/lib/BCGen/HBC
hermes/utils/build/build/lib
hermes/utils/build/build/lib/SourceMap
hermes/utils/build/build/lib/FrontEndDefs
hermes/utils/build/build/lib/AST
hermes/utils/build/build/lib/Inst
hermes/utils/build/build/lib/Regex
hermes/utils/build/build/lib/Parser
hermes/utils/build/build/jsi
hermes/utils/build/build/external/llvh/lib/Support
hermes/utils/build/build/external/dtoa
```
